### ISSUE TITLE
Texygen and OpenAI gym

### ISSUE THREAD

**Issue by mostafachatillon** [geek-ai/Texygen#5]
Why did you build your benchmark from scratch, instead of using OpenAI gym? 
https://github.com/openai/gym

A comparison of your environment vs OpenAI gym would be appreciated

**Comment by desire2020** [comment]
Basically, the text generation problem can be solved through reinforcement learning. However, this is not the only solution, even not the currently best one since it can not stably overperform MLE according to our previous survey. We do not want to limit our platform to those REINFORCE-based models, and we do not want to introduce unnecessary dependencies with other project(s). Hope this helps.
